### ISSUE TITLE
Refactor test_form_limit.rb

### ISSUE THREAD

**Issue by jwindmuller** [rpmsoftware/Watir-Regression-Tests#1]
As we've discussed, we want to see this new framework more fleshed out as to how the tests will look. Use this issue to refactor [test_form_limit.rb](https://github.com/rpmsoftware/Watir-Regression-Tests/blob/master/TestSuite/test_form_limit.rb) to make it more closer to how you think the tests should look like.

**Comment by rpmabhishek** [comment]
As per our last discussion, I am just  adding the existing testcases to the new Framework and I am not breaking them as of now.
